language: node_js
node_js:
  - 6
  - 8
  - 10
  - 12
os:
  - linux
  - osx
  - windows
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libasound2-dev
notifications:
  email: false
