language: node_js
node_js:
  - 6
  - 8
  - 10
  - 12
os:
  - linux
  - osx
  - windows
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - libasound2-dev
notifications:
  email: false
# Travis has no snd-dummy driver (https://github.com/travis-ci/travis-ci/issues/1754)
# preventing our tests from running. Instead we disable the default `npm install`
# installation step and run it as test script so compilation errors will mark the
# build as failed.
script:
  - export CXX=g++-4.8
  - npm install
